version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  file_default:
    class: logging.FileHandler
    filename: log/default.log
    formatter: default
  file_access:
    class: logging.FileHandler
    filename: log/access.log
    formatter: access
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - console
      - file_default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - console
      - file_access
    propagate: no
root:
  level: INFO
  handlers:
    - console
    - file_default
  propagate: no
